### ISSUE TITLE
Create skeleton for all currently planned pages

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#124]
For each page where we have some indicator in the sitemap of a potential page, create a minimal page with the following content (if no full implementation exists):

- [x] title 
- ~~[ ] summary~~
- [x] create banner with link to playground version
- [x] add link to figma frame in banner, if available

Update: I chose to only create these pages for links in the footer. We can create more placeholder pages for planned pages as they become reachable from pages ported from Playground pages into the Next.js pages.

**Comment by agarwal** [comment]
> Update: I chose to only create these pages for links in the footer.

I think that could be okay. Conceptually the goal of this issue is to go end-to-end as much as possible. If there's a link, clicking the link should go to a page that is as complete as possible. But also if the page has been designed or thought of, and there is no link to it, that is also a good page to add because it will force us to consider why it is not linked from anywhere.

**Comment by agarwal** [comment]
When you check off sub-tasks in an issue, can you please add a comment like the following so it is clear when and how they got resolved.

---

> - title 
> - create banner with link to playground version
> - add link to figma frame in banner, if available

Done in #123.

---

Note I removed the checkbox when quoting the items, so that we don't appear to have additional sub-tasks here.

**Comment by ghost** [comment]
> clicking the link should go to a page that is as complete as possible

The first bullet in the various "Implement" issues can track progress on moving from Playground to NextJS page

---

I'm going to mark this issue as done after I have created empty pages for all remaining Figma designs. I'll track the porting of the "summary" sections to NextJS pages with a subtask in the "Implement PAGE: Header component" issues

**Comment by agarwal** [comment]
> I'm going to mark this issue as done after I have created empty pages for all remaining Figma designs. I'll track the porting of the "summary" sections to NextJS pages with a subtask in the "Implement PAGE: Header component" issues

Agreed. Adding the summary goes beyond creating a "minimal" page, which was the core request of this issue.

**Comment by ghost** [comment]
The remaining pages were added in #206

**Comment by ghost** [comment]
Can close this after issues are created for any follow-up work desired based on a second round of PR feedback. If there is no feedback on updated PR within a few days, close this issue.

**Comment by agarwal** [comment]
I didn't review #206 too carefully, but I'm assuming you basically got all the pages in. We had one comment there about whether a Papers Archive page should be created right now or not, and looks like you did create (I see new file `res_pages/resources/ResourcesPapersArchive.res`).

All looks good to me, so I'm closing this issue. I've crossed out the original request for summaries based on our discussion above: https://github.com/solvuu-inc/next.ocaml.org/issues/124#issuecomment-801403295.
