### ISSUE TITLE
Add support for OCaml build scripts

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#13]
Select a procedure for installing dune, opam, and ocaml compiler, that can work reasonably fast with either Vercel, Netlify or ocurrent, so that ocaml scripts can be used as part of the build.

Once a method has been selected, use that method in the build.

EDIT (Mar 11, 2021):
The purpose of this is to enable more complex build steps, e.g. post-processing html or pulling data from an API. We want to implement a CLI tool in OCaml that would get invoked by our build.

**Comment by agarwal** [comment]
I'll add that a lock file is really important. AFAIK opam still doesn't support that, so esy might be the better choice.

**Comment by ghost** [comment]
I tried esy and Vercel didn't provide any useful support in debugging errors installing esy. I need to either dive deep into that error, or start reading web suggestions for installing ocaml compiler on systems like travis and circleci, so that I can imitate travis instructions on vercel

**Comment by ghost** [comment]
> opam still doesn't support that

Correct. When 2.1.0 gets out of beta, then the feature will be available. We should watch this (https://github.com/ocaml/opam/releases) or discuss.]ocaml.org for such an announcement, if we want to try opam later.

**Comment by ghost** [comment]
https://github.com/actions-ml/setup-ocaml - recently updated

**Comment by ghost** [comment]
For integrating with circle-ci/github actions/ocurrent, Netlify exposes a high level command (https://docs.netlify.com/cli/get-started/#manual-setup/) , while Vercel requires a use of it's low level "Vercel client" to access directory upload feature, so it will be simpler to implement a fast ocaml compiler and dependency install with circle-ci/etc calling out to netlify

**Comment by ghost** [comment]
Since Netlify cli is slightly more powerful than Vercel, I'm recommending using Netlify going forward. We can use ocurrent, circleci, or github actions to run the build. I prefer circleci.

**Comment by ghost** [comment]
At this point, neither tutorials, nor ocaml planet, is slated for first release, so this issue can happen after the first release. It still would be nice to have as we could create a small cli tool for the build in ocaml. We have also briefly talked about using dune promote to handle fetching and saving data within the source tree.

Update (April 2021): tutorials have become a focus for the early releases again.

**Comment by agarwal** [comment]
@rdavison As we discussed, our goal is to have an idempotent `make install-deps` command and directory based project configuration. Devs should be able to cd to their local clone and run `make install-deps`, and _all_ dependencies should be installed exactly the same for all devs.

**Comment by ghost** [comment]
Ashish asked if there are any beta or upcoming features that will make opam as simple to use as esy for dependencies isolated to a single project. (i.e. anything simpler than switches?). This question is orthogonal to esy and opam locking.

**Comment by ghost** [comment]
I think ocaml.org should aim to support macos and linux. My limited understanding is that esy implicitly tries to support windows also, since it runs on top of node? Does this implicit support of windows make esy packages or overrides more complex or does it have no noticeable effect?

**Comment by agarwal** [comment]
Review of #257:
- [ ] Delete `description` field in the new `esy.json` file. It contains a copy/paste error.
- [ ] You stated "In addition, I added an example `hello_world` script", but I don't see it.

**Comment by agarwal** [comment]
> This question is orthogonal to esy and opam locking.

Not getting it. I think it is related. If opam has directory based project configuration and good lock file support, then we could use opam instead of esy, right? Or am I missing something?

**Comment by ghost** [comment]
> we could use opam instead of esy, right

Correct.

I haven't read up on how switches and lock files interact. After further reading, I may realize that people use them together.

**Comment by ghost** [comment]
One other left field consideration. If opam or esy manages to implement dependabot integration soon, I would choose whichever tool accomplishes it first. Open issue - https://github.com/dependabot/dependabot-core/issues/2116

**Comment by agarwal** [comment]
> If opam or esy manages to implement dependabot integration soon, I would choose whichever tool accomplishes it first.

That would be nice, but I wouldn't let that override the other two feature requirements. Directory based project configuration and lockfiles are critical.

**Comment by ghost** [comment]
If you had to hold back any dependencies to lower versions than the current latest, please add a documentation comment to `esy.json` indicating that fact.

**Comment by ghost** [comment]
I think there is a chance that we might not need an ocaml build tool. If the rescript compiler team implements the feature which would obviate needing #140 soon, and we forgo the desire to convert a `data/globals.yaml` into a `Globals.res` module, then the only remaining area that might need an OCaml build script would be post processing of Manual html chunks. If we don't end up needing to post process any Manual html, then there will be no remaining use cases for an ocaml build tool.

Regardless, having esy and dune available will definitely be useful and needed. I am already making use of dune.

**Comment by agarwal** [comment]
The list you provide that would obviate the need for an OCaml build tool is unlikely to be fulfilled anytime soon, if ever.
