### ISSUE TITLE
Integrate Manual into the site

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#130]
The OCaml Manual is hosted on ocaml.org, and we need to style it to match the site. Also we want to enhance the rendering to include features like a table of contents in a left navbar. This might need to get split into multiple issues, but for now we think the following tasks are required:

* Understand the recent work in https://github.com/ocaml/ocaml/pull/9755.
* Summarize a strategy for addressing this issue. As can be seen in the comments of the above PR, there are several decisions that need to be made.
* Generate html from the manual's source files (which might be latex or html, depending on what we decide above). A first pass could do the minimal necessary. Then we can add features like table of contents, improve the styling, etc. We are thinking of creating a tool something like `ocamlorg ocaml-manual chapter1.[tex|html]` that would output an `.html` or `.res` file. This tool would use the `lambdasoup` library.

In future, we could consider whether to modify the source of the manual itself. This was proposed as a possibility at https://github.com/ocaml/ocaml/pull/9755#issuecomment-657465339. Note we are hesitant to start with this as it would likely delay everything above significantly.

**Comment by ghost** [comment]
Consider finishing #138 before getting too deep into this task. Similar to the manual, the release page needs to receive externally formatted content, apply additional formatting, and then glue the result together with the site header and footer.

**Comment by agarwal** [comment]
@rdavison I have updated this issue's original description. Please review.

**Comment by ghost** [comment]
Richard might find it useful to quickly skim #117.

**Comment by ghost** [comment]
Most people reading the manual will read it in pieces, when they need specific information. I don't expect it to be consumed as a book. I am used to languages presenting such information spread over a series of webpages. Its been many years since I have seen options to download a pdf or other format mentioned. I think rescript-lang is also heading in the right direction for presenting language reference material.

In light of these current times and that context, I don't see the purpose of producing anything besides html. If html is the only real output, then markdown is sufficient and latex is unnecessary complexity.

Even if we agree that markdown is sufficient, it might not be feasible to rewrite the content into markdown in the short term. In such a case, we might want to come up with a transitional plan to reach rewriting source files in markdown at a later point.

**Comment by agarwal** [comment]
The request in this issue does indeed target only HTML as an output.

In regards, to what the source format for the manual should be, yes I want to leave that to future work. We'd have to explore the better option and discuss with the authors whether they want to move to that.

> then markdown is sufficient and latex is unnecessary complexity

That's not immediately clear to me. The manual contains math syntax, and I'm not sure how that would get done in Markdown. There might be other features too, like references that need to be considered. I think some research is needed to determine the best format for authoring and publishing books in the modern era.

**Comment by agarwal** [comment]
> The request in this issue does indeed target only HTML as an output.

I did suggest that we might output `.res` files instead of HTML, but conceptually that's not too different. It would largely be a block of HTML.

**Comment by ghost** [comment]
> I think some research is needed to determine the best format for authoring and publishing books in the modern era.

My biggest question is: should it be a book? I see "Real World OCaml" clearly as a book. I am not sure about the manual.

What I like about ReScript's presentation of the reference material is that beginners and experienced users create GitHub issues to request specific additions or changes. Right now, with the manual spread across two repositories and being organized as a book, ocaml beginners and regular users might be less likely to open an issue in the ocaml.org github repository to request a small improvement to the manual.

**Comment by ghost** [comment]
Most likely, `rehype-parse` will be useful for any transformations which we implement in ReScript.

**Comment by agarwal** [comment]
> My biggest question is: should it be a book?

I see, well it currently is. Changing that is probably hard, and I wasn't thinking about that.

**Comment by ghost** [comment]
PR #445 is moving towards shifting any Manual processing into `ood`.

**Comment by ghost** [comment]
This issue is superseded by https://github.com/ocaml/v3.ocaml.org-server/issues/93.
