### ISSUE TITLE
Implement "History" page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#139]

**Comment by ghost** [comment]
Done in #218

**Comment by agarwal** [comment]
We still need to link this new page from somewhere.

**Comment by ghost** [comment]
Add "About OCaml.org" to the footer and link to the history page from the bottom of the about page, similar to https://developer.mozilla.org/en-US/docs/MDN/About#history_of_mdn_web_docs ?

**Comment by agarwal** [comment]
I'm not sure. The current site has an "About This Site" link in the footer, which goes to a page that includes much other content too. So if that is being ported, then History might be a link within that page. Maybe you could add History to the footer for now, so we we'll easily see it and recall that it needs to considered in the future.
