### ISSUE TITLE
Implement "Homepage: Hero" component

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#142]
We have a design to suggest it should be circular. Also today @avsm pointed out that it flushes right without a margin, and this can look odd in two ways: i) Firstly it is unclear sometimes if you're missing more content to the right or if that's the end of the view. ii) It appears asymmetrical at certain screen widths. See below. You can see the image goes all the way to the right of the window while all other content has a right margin.

<img width="2195" alt="Screen Shot 2021-03-11 at 4 25 12 PM" src="https://user-images.githubusercontent.com/112173/110857075-62d09f00-8286-11eb-8046-00bd19f7232b.png">

Perhaps switching to the circular image should be considered now. It might resolve the first issue, though probably not the second.

**Comment by ghost** [comment]
Consider renaming this `Implement "Homepage: Hero" component`

**Comment by agarwal** [comment]
> Consider renaming this `Implement "Homepage: Hero" component`

Done.

**Comment by ghost** [comment]
Here is a screenshot of a more complete Tailwind example landing page zoomed to a very large desktop screen size:

![image](https://user-images.githubusercontent.com/1385802/124158896-7dfb3080-da68-11eb-9078-0eeec3305bfd.png)

I agree that the hero component's decision to align the text close to the image does appear asymmetrical at this width.

**Comment by ghost** [comment]
If we do not want to change to circular, then #464 might have modified the hero enough to close this issue.

**Comment by ghost** [comment]
@avsm I am going to close this issue for now. Please reopen if you want to change the image into the circular version.
