### ISSUE TITLE
Enable faster Tailwind dev

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#143]
We want to somehow make it easier to write Tailwind components. The feature we need is auto-completion for the values of their classes. A VS Code plugin might do what we want, but @kanishka-work mentioned some other possibilities.

The goal is to cut out the Tailwind playground from our dev cycle. This is a pain point.

**Comment by ghost** [comment]
You can observe toggling through values using arrow keys in this video clip: https://www.youtube.com/watch?v=eCWhTZ34Hck&t=233s

**Comment by agarwal** [comment]
I'm feeling more and more that we should stop using the Tailwind playground, except for very ad hoc initial prototyping. The only value of it is getting some autocompletion, but the cons outweigh this one benefit. Our code needs to be in this repo, not in a collection of unstable URLs in the Tailwind playground.

**Comment by ghost** [comment]
Once we copy the current Playground pages into the site, we can remove all references to the Playground from the codebase. As noted in Slack, my original hope was to go through many iterations of concepts/designs for a single page within a few days (sort of like having PR under active review), and then promote a page from "prototype" to "polished" by copying the resulting prototype into the real codebase. We haven't gotten into a fast iteration workflow, so the Playground pages have become a needless intermediate step.

We will need to use the Playground for onboarding new developers to this project, unless they have extensive experience with CSS. There is a large surface area of primitives and combinations one needs to be familiar with in CSS to be proficient in contributing to the site. The Tailwind quick reference documentation is over 60 pages long. Many of those pages refer to simple properties like text color or margin, but others refer to more complex concepts like grid, flexbox, and positioning. One way to build up the familiarity needed is to keep trying out combinations of CSS snippets until you are aware of how to properly use the primitives together. We might ask new developers to visually observe some portion of the site, and recreate it in Tailwind Playground.

**Comment by agarwal** [comment]
Got it. Thanks for the explanation. Perhaps the criteria should be "Don't leave code in the Tailwind playground for too long".

Regarding your second point, it's currently unclear who will implement new Tailwind components. It's a harder task that might be on the core team forever, and also we haven't yet figured out the Tailwind license that would even allow it.

**Comment by ghost** [comment]
> . It's a harder task that might be on the core team forever, 

I assumed so, but even the core team will likely always be stronger on ReScript/ocaml than css, so I want some way to keep ramping new full time devs on css. Maybe we need to find the best o'reilly and other css books and document a ramp path. I still place myself at intermediate level and could benefit from finishing this ramp path.

**Comment by ghost** [comment]
> The feature we need is auto-completion for the values of their classes

This cheatsheet for the tailwind classes might help also - https://tailwindcomponents.com/cheatsheet/

**Comment by ghost** [comment]
We are moving towards restricting the total number of custom components, and aiming to have enough custom components so that most new pages can mix and match existing components. This should reduce how often one needs to directly design and use lower level Tailwind CSS.

**Comment by ghost** [comment]
Other useful tools for css ramping: webflow and Figma auto layout.

I am closing this issue since we have a working path forward:

* expand reusable component and page layout library to reduce the amount of css being worked on
* keep finding resources for fast css ramping for new devs
* don't use tailwind playground to present page implementations
* possibly use tailwind playground when designing new reusable components

If desired, we can create a follow up issue to add tailwind autocomplete extensions to vscode.

**Comment by agarwal** [comment]
👍
