### ISSUE TITLE
Port opam.ocaml.org into this site

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#146]
The opam.ocaml.org website consists of opam packages and a description of the opam tool. For all pages focused on the opam tool, port them to this site. The site has the following sections:
- [ ] Landing page. This provides summary statistics, a table of new packages, news, etc. Only port the hero section, news, contribute, and documentation sections of the page.
- [ ] Documentation
- [ ] About opam
- [ ] Platform blog

**Comment by agarwal** [comment]
I updated the main description to list the components of opam.ocaml.org and updated the title.

**Comment by ghost** [comment]
I updated "Landing page" and removed "Packages", to reflect what I understand is the boundary between the upcoming site docs.ocaml.org, which will list packages similar to this example https://b0-system.github.io/odig/doc/, and www.ocaml.org/opamtool/ which I currently understand as only dealing with the opam tool executable. Feel free to revert my edit if you understand the goal differently.

**Comment by agarwal** [comment]
I'm also not entirely clear on it yet. We can refine as we get more information.

**Comment by ghost** [comment]
Closing this issue for now, as it has been assigned to other developers. We can reopen if someone in this group or outside starts to merge changes into this repository.
