### ISSUE TITLE
Add VS Code configuration for Rescript

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#15]
We should determine the desired VS Code plugins and their configurations, and encode that in a VS Code config file.

**Comment by ghost** [comment]
Is it okay if I assign this one to you, since you might already be familiar with them? If you prefer that I do it, that's fine also.

I would like us to include this in the repo, but not actively promote it in the README, because I fear as soon as the ReScript lang team is short on budget or resources, the first thing that will be neglected will be maintaining these IDE features.

**Comment by agarwal** [comment]
Good editor support is something the front-end community values a lot, and VS Code is one of the 2 [recommended](https://rescript-lang.org/docs/manual/latest/editor-plugins) editors by ReScript. I was thinking of going the other way and promoting VS Code to be used by any contributors.

I'm not actually an expert on this myself. Still not sure how we've done it in our internal code base. There's a config file but also a workspace, and I never was quite clear on what's what. I think it's worth you figuring it out. We still need you to figure out remote coding and other features, so you might as well dive into this.

**Comment by ghost** [comment]
I was planning on recommending VSCode, but not mentioning the plugins. I will read up on the plugin maintenance history and see if Patrick is keeping pace with the bucklescript compiler or falling behind.

**Comment by ghost** [comment]
Issue tracker and commit activity on the plugin are pretty healthy. I will stick with noting vscode, and providing a config file, but will not promote the plugins actively. I don't want to have to answer questions if people have problems using the plugins. After I use the plugins for six months, if they work well throughout that time, then I will mention them on the readme also.

**Comment by agarwal** [comment]
> I was planning on recommending VSCode, but not mentioning the plugins.

I think the specific choice of plugins is part of the developer experience. In our internal code, it is essentially required that you install the same plugins and use the same config. There is some flexibility. A config that sets code formatting is not a personal choice, but a config that lets you see inline types is because it doesn't change the code eventually committed. VS Code supports this kind of separation.

**Comment by ghost** [comment]
On a related note, a Reason Discord thread mentioned that the vscode plugin uses this tool `./node_modules/.bin/bsc -format <path to file>`, not `refmt` when formatting ReScript files.

**Comment by ghost** [comment]
Reason discord thread discussing some problems and whether to run rescript in a separate process or not: https://discord.com/channels/235176658175262720/235199119747055616/796771502107525170

**Comment by ghost** [comment]
Might be useful: https://github.com/tailwindlabs/tailwindcss.com/blob/master/jsconfig.json

**Comment by ghost** [comment]
I referenced this discussion (https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control) of vscode .gitignore suggestions while working on this issue.

**Comment by ghost** [comment]
- [x] Apply formatting to all files in a separate PR

**Comment by ghost** [comment]
>  Apply formatting to all files in a separate PR

Done in #159

**Comment by ghost** [comment]
We may want to add "run rescript:format" as a manual task to perform as part of each ReScript version upgrade. I'm not going to create a task for that yet. Future ReScript upgrades may introduce only small changes in formatter behavior and make such a task unnecessary. I'll watch the next few ReScript upgrades and then update the upgrade workflow instructions if it becomes necessary.

**Comment by ghost** [comment]
The rescript extension was added in #155
