### ISSUE TITLE
Implement "Industrial Users: Main Content" component

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#150]
...

Subtasks:
* define content structure for industrial users database and populate with sample data

**Comment by ghost** [comment]
Most of this was completed in PR #217 (along with the follow-up PR #232 )

Remaining work:
* Parse companies data content from yaml

**Comment by agarwal** [comment]
@kanishka-work Your last comment states there is more work to do, but this issue was moved to `Done`. Please clarify.

**Comment by ghost** [comment]
I will correct the status. I probably made a mistake.

**Comment by ghost** [comment]
This is now a duplicate of #415.
