### ISSUE TITLE
Purge practice pages from site

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#154]
While waiting for the new site design to start, I created many practice pages imitating the old site to develop speed with Tailwind. Some of the pages demonstrate useful techniques such as rendering markdown. Save links to useful pages in the Wiki. Delete all practices pages after that.

**Comment by agarwal** [comment]
If any are useful to maintain live, you could keep them under a `/dev` URL path.

**Comment by ghost** [comment]
Done in #226
