### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#16]
@agarwal Please enable dependabot on this repository. I believe you will find a dependabot tab on this page: https://github.com/solvuu-inc/ocamlorg2/network/alerts . The end result that I hope to see is the presence of a few automated PRs for the out of date dependencies in this repo.

**Comment by agarwal** [comment]
Done. It also required me to enable `Dependency graph`. The settings now look like this:

<img width="850" alt="Screen Shot 2020-12-16 at 5 21 41 PM" src="https://user-images.githubusercontent.com/112173/102413699-57414500-3fc3-11eb-94bd-c363ee1a9807.png">

**Comment by ghost** [comment]
I also skimmed this guide(https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates) and created a dependabot.yml file. I will wait to see PR's created and close this issue once we see those.

The rescript-nextjs-template doesn't have a dependabot.yml file, so I'm not sure if its still necessary. I didn't see PR's created right away, so I added the file to see if it will help.

**Comment by ghost** [comment]
![Screenshot from 2020-12-16 17-42-59](https://user-images.githubusercontent.com/1385802/102415473-39291400-3fc6-11eb-8715-875b1f2cb312.png)
It worked after I moved the file into `.github/dependabot.yml`
