### ISSUE TITLE
Implement header navigation mobile dropdown panel

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#172]
This issue narrowly deals with selecting a dropdown menu component from the available tailwind options (https://tailwindui.com/components/marketing/elements/headers) for the mobile dropdown menu and then deciding on initial content to populate the menu.

**Comment by agarwal** [comment]
The hamburger menu that shows up in small screens doesn't work. Is that what this issue is requesting to fix?

https://user-images.githubusercontent.com/112173/111554114-15f43900-875c-11eb-9b3b-21bfad7cc97a.mov

**Comment by agarwal** [comment]
> The hamburger menu that shows up in small screens doesn't work. Is that what this issue is requesting to fix?

@kanishka-work answered in https://github.com/solvuu-inc/next.ocaml.org/issues/125#issuecomment-801521171. That's the issue that will implement basic technical functionality. This issue requests to implement the menu with a design we like.

I think we can simply merge the two goals by defining "design we like" as the following image. That's it for now. We'll create a new issue when and if we provide an alternate design. Note that in the image below the right angle bracket doesn't need to be collapsible. I'm using it only as a visual marker to separate out the menu categories.

![Scannable Document on Mar 19, 2021 at 11_07_23 AM](https://user-images.githubusercontent.com/112173/111801433-55796d00-88a3-11eb-95bb-c939fa7de547.png)

**Comment by ghost** [comment]
I went with the following slight modification to avoid deviating from the standard Tailwind UI code:

![Screenshot from 2021-03-23 16-59-47](https://user-images.githubusercontent.com/1385802/112223073-c603ef00-8bff-11eb-8201-3f5d122f693e.png)

**Comment by ghost** [comment]
Done in #209

**Comment by agarwal** [comment]
Design is definitely lacking, but it is functional. I'm closing this issue. We'll create a new issue for design improvement when that is available.

**Comment by ghost** [comment]
the new design is available, FYI

**Comment by agarwal** [comment]
Okay, please create new issue to implement the new design.
