### ISSUE TITLE
Provide clean commands in Makefile

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#199]
Our Makefile should provide:
- [x] `clean`:  This should remove all build artifacts, but not remove caches that take a lot of time to create nor dependencies such as `node_modules`.
- [ ] ~~`clean-cache`: Remove also build artifacts that take a long time to build. We don't have anything like this yet but are anticipating it.~~
- [x] `distclean`: Also remove dependencies such as the `node_modules` directory.

Also:
- [x] https://github.com/solvuu-inc/ocamlorg2/pull/156#discussion_r594750721
- [x] https://github.com/solvuu-inc/ocamlorg2/pull/156#issuecomment-799825108

**Comment by ghost** [comment]
We need to think carefully about `yarn`.

**Comment by rdavison** [comment]
> We need to think carefully about yarn.

What about yarn do you think merits careful thinking?

**Comment by ghost** [comment]
> What about yarn do you think merits careful thinking?

This might be moot now. At some point, we installed `yarn` using `npm install yarn` as a local dependency, which added yarn to the `package.json` file. I was concerned that we would clean the `node_modules` folder and lose `yarn`. (At present, `yarn` is not in `package.json` since we do not use `npm install yarn` currently.)

**Comment by rdavison** [comment]
> https://github.com/ocaml/v3.ocaml.org/pull/156#discussion_r594750721

Left it as is. `bsb -clean` seems to be the right solution to me.

> https://github.com/ocaml/v3.ocaml.org/pull/156#issuecomment-799825108

Done as part of https://github.com/ocaml/v3.ocaml.org/pull/351

**Comment by rdavison** [comment]
Closing this issue as I believe it's done.
