### ISSUE TITLE
Configure VS Code settings

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#200]
In #15, we provided a `.vscode/extensions.json` file. We should also provide a `settings.json` file that does at least the following:
- [x] Configure VS Code to format rescript files upon save.
- [x] Also do this for .js and .json files. Not sure if that is automatically done, but we have such files, so should assure they too are formatted consistently.
- [x] Set `files.insertFinalNewline` to `true`. We are often committing files without a final newline.

**Comment by ghost** [comment]
> Configure VS Code to format rescript files upon save.

I didn't dig deeply, but I thought I observed this happening already.

**Comment by agarwal** [comment]
Just tried. Not working for me.

**Comment by ghost** [comment]
Some web advice says to not check in settings.json, but instead provide a settings.json.sample and provide instructions for copying that file into place, so that there aren't constant git conflicts between someone's local environment and the master branch. I don't believe that applies to us since we are a small team and don't expect many open source contributors. If we get up to ~10 regular contributors modifying ReScript code, we should move to a settings.json.sample file then.

**Comment by agarwal** [comment]
Interesting. I think it is the exact opposite. We want to check in the settings.json to assure that there are no mismatches between an individual developer's edits and master.

**Comment by ghost** [comment]
>> 
>  *   Configure VS Code to format rescript files upon save.
> * Also do this for .js and .json files. Not sure if that is automatically done, but we have such files, so should assure they too are formatted consistently.
> * Set files.insertFinalNewline to true. We are often committing files without a final newline.

Done in https://github.com/solvuu-inc/next.ocaml.org/commit/8383b60163b89af519bc4ab4d87075d053358691 (Sorry, accidentally commit to master. Feel free to leave comments there or in this issue and I will address them).

**Comment by agarwal** [comment]
- [x] I asked a question at https://github.com/solvuu-inc/next.ocaml.org/commit/8383b60163b89af519bc4ab4d87075d053358691#r48466461
- [x] I don't see a `settings.json` file.

**Comment by ghost** [comment]
> I don't see a settings.json file

Noticed this also after you pointed out .gitignore bug. It's in the follow-up PR, https://github.com/solvuu-inc/next.ocaml.org/pull/204/files#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357

> I asked a question at 8383b60#r48466461

Answer there, will apply change in PR soon.

**Comment by agarwal** [comment]
I QA'd. This looks good. But I did notice a related problem, for which I created new issue #207.
