### ISSUE TITLE
Implement "Milestones" page and progress bar

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#203]
- [x] We want a page showing the milestones of the current project.
- [x] Also display a progress bar showing percent completion. This could either go in the `milestones` page or perhaps should be a thin banner at the top of all pages.

**Comment by ghost** [comment]
You might be interested in applying this workflow as you and I continue to implement this: [Development Workflow Steps](../wikis/Development-Workflow-Steps)

**Comment by ghost** [comment]
>  * We want a page showing the milestones of the current project.
> * Also display a progress bar showing percent completion. This could either go in the milestones page or perhaps should be a thin banner at the top of all pages.

Done in #218
