### ISSUE TITLE
VS Code formatting should match Makefile command

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#207]
We provided a Makefile target `rescript-format` and also configured VS Code settings to format rescript files. As of d4b5672df43d2ef8726930eb62ef40098d1184f1, their behavior doesn't match. I found one example:

- Running `make rescript-format` does not change `res_pages/community/CommunityAroundWeb.res`. However, opening that file in VS Code and hitting save does cause some changes.

**Comment by ghost** [comment]
One this issue is complete, create a follow up issue to add husky and use it to run rescript-format pre-commit

**Comment by ghost** [comment]
Look to see if bsc format has plans to support editorconfig settings

**Comment by ghost** [comment]
When we used an automatic code formating on a large scala code base over the course of a few years, we found that the formatter introduced noise in our git history with each upgrade of the formatter library. As much as I like having automatic formatting, I am unsure if it is a net benefit. I might prioritize cleaner git history over some manual effort by developer.

---

For now, I will remove the rescript-format command as I would not want someone to format all files in batch, especially if they were doing this after upgrading the formatting library. We can require that all developers use vscode for now and revisit creating a command line to format an individual file for vim and emacs users later.

**Comment by ghost** [comment]
> I will remove the rescript-format command

Done in #319. RIP.
