### ISSUE TITLE
Trim JS rewrapping modules to the bare minimum needed

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#21]
#19 Addressed properly wrapping rescript page modules with JS. This issue involves reducing the code in each of these boilerplate files down. This example (https://github.com/reason-association/rescript-lang.org/blob/master/pages/blog/%5Bslug%5D.js) is probably the least amount of code to accomplish the same behavior. Try using that and replacing existing wrappers with that code instead.

**Comment by ghost** [comment]
The rescript nextjs starter was updated. It now notes that the more explicit rewrapping of React components might be needed for fast refresh to work.

**Comment by ghost** [comment]
Change to draft pr

**Comment by agarwal** [comment]
I can't tell why this issue was closed.

**Comment by ghost** [comment]
This was when I started shifting towards the workflow in the readme, which you and I should finalize soon, as noted in prior PR comment.
