### ISSUE TITLE
Generalize markdown driven page component

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#222]
"Install OCaml" demonstrates a markdown driven page. Generalize it's implementation, attempting to deal with all of the following issues:

- [x] Use a generic page component which renders all markdown files within a given directory (or directory subtree, if preferred). `getStaticPaths` should help in implementing this
- [x] Consider how the markdown file names will map to urls
- [x] Initially use `a` tag for all links
- [x] Refactor link generation to use NextJS Link component for internal links or accept limitations of not using NextJS Link component in this situation.
- [ ] Improve general text and code block styling. Do not address highlighting in this issue. Highlighting will be dealt with in #137.

Note: Create a follow-up issue to design and implement the mobile rendering of the table of contents.

**Comment by ghost** [comment]
> *    Use a generic page component which renders all markdown files within a given directory (or directory subtree, if preferred). getStaticPaths should help in implementing this
> *    Consider how the markdown file names will map to urls
> *    Initially use a tag for all links

These were all done in #252

**Comment by ghost** [comment]
> Refactor link generation to use NextJS Link component for internal links or accept limitations of not using NextJS Link component in this situation.

As part of #296 , I chose to use rehype-stringify, which does not allow for React elements. Since we cannot use React elements, I have chosen to accept the limitations of not using NextJS Link component in the body of rendered markdown.

**Comment by agarwal** [comment]
@kanishka-work Consider closing this and making followup issues for design improvements.

**Comment by ghost** [comment]
> Improve general text and code block styling. Do not address highlighting in this issue. Highlighting will be dealt with in #137.

We'll create a follow-up issue for this.
