### ISSUE TITLE
Use less strict types in footer

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#228]
Originally, I wanted to use the compiler to help identify code which needs updating if an entry is added or removed from footer.

I would rather have the menu be completely driven by lists of data. Change the type to use a list of nav entries. The urls in the nav entries should directly reference values which represent known urls, rather than using string literals.

Create a follow up task to do the same thing for the header navigation

**Comment by ghost** [comment]
As part of this issue, let's also define the lists of entries using a string constant with yaml text, use a yaml parser.

Nextjs doesn't currently allow for getStaticProps functions in app.js (https://github.com/vercel/next.js/issues/12434) but having the yaml parser ready in anticipation of when nextjs provides this would be nice.

**Comment by ghost** [comment]
I would categorize this issue under "General" since issues related to the header navigation fall under "General".

**Comment by agarwal** [comment]
Okay. I moved it.

**Comment by ghost** [comment]
I chose not to create a literal yaml string for now.
