### ISSUE TITLE
Evaluate ocaml code in markdown files

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#229]
- [x] Perform a spike to review the features of ocaml-mdx and explore ways to invoke it.
- [x] Take an inventory of all ocaml evaluation features used in existing tutorial markdown files.
- [x] Add ocaml-mdx as an opam dependency.
- [x] Add example tutorial file and use `dune` to evaluate ocaml top level snippets.
* ~~Update `make ci-build` to perform `dune runtest` on all tutorials and fail if the exit code is not zero.~~ The tutorials are moving to the `ood` repository.
* ~~Create follow-up issue to document dune editing workflow.~~ The tutorials are moving to the `ood` repository.
- [ ] Clean up code merged in #302. Remove logic that is now redundant with `ood` such as the `ocaml-mdx` dependency.
- [ ] Create a follow-up issue to factor out retrieving tutorial files into a Tutorials module.

**Comment by ghost** [comment]
> * Take an inventory of all ocaml evaluation features used in existing tutorial markdown files.

I surveyed all the tutorials and any other pages that use ocaml evaluation or highlighting. I ignored 99 problems, as I understand the future of that page is still under discussion. I found the following annotations:

* console
* ocamltop
* ocaml
* text
* C
* shell
* python
* SQL
* java
* assembly
* sh
* Pascal

Currently, only ocaml and ocamltop invoke any special logic.

**Comment by ghost** [comment]
> * Perform a spike to review the features of ocaml-mdx and explore ways to invoke it.

Done in #290

**Comment by ghost** [comment]
Currently, we are leaning towards using ocaml-mdx directly in `getStaticProps`, as most tutorials on ocaml.org deal with primitive concepts in ocaml.

We could have introduced dune as an intermediary. This would allow for arbitrarily complex chains of libraries to be referenced from ocaml code snippets, but it would also introduce some drawbacks. As I currently understand it, dune would require two steps of processing, so it would not smoothly integrate with rendering markdown during page rendering. Either the user will use two windows to edit and inspect the markdown transformations, or some integration would need to be implemented in the markdown rendering to show proposed changes in a draft mode and allow the user to tell dune to promote a draft.

**Comment by ghost** [comment]
In the dune based workflow, we can combine the two methods that I was considering. A user can choose to edit a markdown file and manually use dune promote to accept the changes after inspecting them. At the same time, in hot reload mode, when a user visits a page, getStaticProps can perform dune auto promotion before proceeding to render a markdown file. If we choose this hybrid approach, we can implement the dune auto promotion call as an enhancement.

**Comment by ghost** [comment]
For the first implementation, I will assume the tutorial author has used `dune` with `ocaml-mdx` to evaluate code snippets in the tutorials. When the tutorial is rendered into markdown, we won't invoke `dune runtest` or `dune promote`.

We may decide to later enhance this workflow. The tutorial author can use `dune` normally, but the rendering of the tutorial can also invoke `dune runtest` and check the status code of the process call. If the status code is not zero, then the rendering can fail with an exception noting that the markdown file is not up to date.

**Comment by ghost** [comment]
> * Add ocaml-mdx as an opam dependency.
> * Add example tutorial file and use dune to evaluate ocaml top level snippets.

Done in #302 .

**Comment by ghost** [comment]
> Clean up code merged in #302. Remove logic that is now redundant with ood such as the ocaml-mdx dependency.
> Create a follow-up issue to factor out retrieving tutorial files into a Tutorials module.

These two items remain outstanding.

**Comment by agarwal** [comment]
> Clean up code merged in #302.

How much work is this? Either it should get done fast, within a few hours, or make a new issue of it, so we can close this one.

**Comment by ghost** [comment]
> Remove logic that is now redundant with ood such as the ocaml-mdx dependency.

This portion of the task was done in PR #364.

**Comment by ghost** [comment]
This remaining todo's in this issue are no longer relevant after PR #445.
