### ISSUE TITLE
Select json decoding library

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#253]
Here are some hits:
- https://github.com/nkrkv/jzon
- https://mlms13.github.io/bs-decode/docs/what-and-why
- bs-json - This is used by rescript-lang.org.

Check which libraries are being maintained (e.g. is it using rescript syntax?), consider APIs. Identify the library selected by rescript-lang.org.

**Comment by ghost** [comment]
#252 demonstrates json decoding logic that we want to improve.

**Comment by ghost** [comment]
Maybe this is overkill. We can just bind the result to ReScript record and let the code throw an exception if a field is missing. Each page module can define it's own binding for yaml parse.

**Comment by ghost** [comment]
When binding directly to a ReScript record, a page doesn't throw an exception if a field is missing, it just uses the js value "undefined" and renders the page with the value "undefined"

**Comment by ghost** [comment]
>  bind the result to ReScript record and let the code throw an exception if a field is missing.

Will be done in #287

**Comment by ghost** [comment]
I selected the following approach. Each use of yaml load defines a distinct binding where the result type matches the exact shape of the JS object with a corresponding ReScript record type. This is very similar in spirit to the default approach recommended in the ReScript manual. Since ReScript does not validate that the runtime data matches the declared type, I also introduced a pattern for defining a utility function to force validation of the data by accessing each field.

There are two small drawbacks to the approach selected here:

1. We have to manually keep `forceInvalidException` and the type definition in sync. This is a minor inconvenience.
2. We repeat the bindings for JsYaml everywhere. This is a minor issue.

**Comment by ghost** [comment]
If we decide that having accurate errors with line numbers is important, then we might want to revisit using Json decoding. Alternatively, the force exception function could print the object as part of the exception, to provide more context.

**Comment by agarwal** [comment]
> There are two small drawbacks to the approach selected here

Please explain the approach that was selected. I kind of get it by reading the PR, but this seems worth an explicit explanation.

**Comment by ghost** [comment]
There are two issues that need to be addressed.

1. We need to prepend process.cwd when determining the file path for a yaml file. (https://nextjs.org/docs/basic-features/data-fetching#reading-files-use-processcwd)
2. All data passed from getStaticProps to a page component needs to be serializable, but we may want richer types in our domain model types. I suggest we use bs-json to go from json.t to the richer type in both getstaticprops and within react components, and we only pass json.t data from getstaticprops to a page component.

**Comment by ghost** [comment]
I spent a few hours searching around for what libraries are available and popular for json parsing in ReScript. Most of the libraries were implemented for bucklescript and seem to be abandoned. Overall, the atd based library from ahrefs and bs-json look promising. The forum also mentions decco. I'll start with bs-json, since I'm unsure if the atd based approach will end up aligning with Melange or ReScript later on. If bs-json doesn't work, then I will drop down to implement more verbose parsing using the ReScript Json standard library.

One other alternative that I won't pursue right now is to use bs-json to convert from Json.t to a domain type, but use genType to deal with transferring ReScript data across Javascript plumbing code. I didn't research genType very deeply. genType needs more tutorial documentation.

**Comment by ghost** [comment]
This work will proceed in two steps:

1. #326 will change the implementation of existing parsing to use bs-json.
2. A follow-up PR will define encoders and make use of encoding as part of `getStaticProps` and decoding as the first step of React page component's `make` function.

**Comment by ghost** [comment]
I just don't like that bs-json hasn't implemented using a Result type, even though a 2018 [closed issue](https://github.com/glennsl/bs-json/issues/41) says that it would be coming soon. bs-aeson (a fork of bs-json focused on haskell interoperability) has a function called wrapResult.

**Comment by ghost** [comment]
I am most excited about bs-decode and jzon. I am holding back on using them because I don't know if either will be as actively maintained as bs-json.

**Comment by ghost** [comment]
Richard feels that its safe to use ReScript libraries that make use of ppx for the foreseeable future, so we can actively consider using `decco` and `atd-codegen` wrapper around `bs-json`, if we want.

**Comment by ghost** [comment]
If we decide to choose bs-decode over bs-json, I propose transitioning slowly. We can start by using bs-json, and introducing bs-bastet as a dependency. Then, let's watch bs-bastet for a while and see whether the maintainers demonstrate a commitment to maintaining it. If we see that bs-bastet is regularly updated, then we can pull in bs-decode and other dependencies and remove bs-json. Below is a graph of bs-decode's dependencies:

![bs_decode_dependencies(1)](https://user-images.githubusercontent.com/1385802/118347022-02700f00-b50e-11eb-85cd-53769aaa50b2.png)

Update: I read through the issues in relude/bs-decode and it sounds like the authors are a little exhausted with dealing with breaking changes in ReScript. I will assume that relude will end up aligned with Melange and remove it from consideration.

Update 2: There seems to be energy from the relude user base to maintain a fork of relude that is ReScript compatible. I don't think we need to rule it out completely.

**Comment by ghost** [comment]
- [ ] Select and implement an abstraction for the common aspects of the `readAll` function

**Comment by ghost** [comment]
> One other alternative that I won't pursue right now is to use bs-json to convert from Json.t to a domain type, but use genType to deal with transferring ReScript data across Javascript plumbing code. I didn't research genType very deeply. genType needs more tutorial documentation.

I am second guessing not pursuing this. We should implement a small prototype and see how complex genType is to use before dismissing it.

**Comment by rdavison** [comment]
I was under the impression that genotype is more about cross language compatibility, and is technically supposed to be phased out eventually. Is the reason we are looking for a json codec more about getting better error messages than you would by just creating bindings?

**Comment by ghost** [comment]
> . Is the reason we are looking for a json codec more about getting better error messages than you would by just creating bindings?

Yes. I had a compromise approach where I bound to the type, but defined an auxiliary function to walk the bound data and force exceptions, but multiple people found it ugly and counterintuitive. 

The biggest problem with ReScript manual's recommendation for binding directly to json data is that mismatched data flows all the way to the rendering and shows up as "undefined", rather than causing a runtime exception.

genType can be used to export values from ReScript to js (nextjs in this case), as well as receive values back from js.

**Comment by ghost** [comment]
If ood merges this PR (https://github.com/ocaml/ood/pull/36), then this issue should focus on removing all json decoding from this repository.

**Comment by ghost** [comment]
- [x] Either trim usage of bs-json or remove it
- [x] Remove gray-matter dependency and all logic depending on it
- [x] Remove js-yaml dependency and all logic depending on it

**Comment by rdavison** [comment]
> If ood merges this PR (ocaml/ood#36), then this issue should focus on removing all json decoding from this repository.

I think a json library could still be helpful, for instance when parsing the Next.js path parameters. Though, I don't expect that parsing logic to be all that challenging. Maybe it would be sufficient to keep our dependencies slim, and just use the low level `Js.Json` module.

**Comment by ghost** [comment]
> Either trim usage of bs-json or remove it
> Remove gray-matter dependency and all logic depending on it
> Remove js-yaml dependency and all logic depending on it

This is done in #445. The internationalization PR will decide whether to implement it's own json parser for the lang value.
