### ISSUE TITLE
Find a maintained, minimal dependency front matter library

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#260]
Currently, we are using gray-matter to parse front matter. It has the following dependencies: 

![image](https://user-images.githubusercontent.com/1385802/113459968-26a3e080-93e5-11eb-9afd-2cd9b535abe2.png)

Are there any smaller dependency libraries available?

Note: This is very low priority.

**Comment by agarwal** [comment]
I agree fewer dependencies are good, all else equal. But if gray-matter is well supported and the dominant library for this, then that could outweigh the disadvantages of it having many dependencies.

**Comment by ghost** [comment]
Okay. Let's close this. I spent about 15 minutes browsing npm and I couldn't find anything both very popular and more slim than gray matter. Gray matter has toml and json parsing. We only need yaml. Good enough for now.
