### ISSUE TITLE
Add .resi interface files for all modules

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#277]
As we shift towards cleaning up the code, add interface files for all modules. The rescript-nextjs starter by Patrick E. leaves these out, but we would rather have them for more explicit documentation.

**Comment by agarwal** [comment]
I was at first thinking that maybe we could omit `.resi` files for the pages files, but https://github.com/solvuu-inc/next.ocaml.org/issues/140#issuecomment-816767061 suggests that we should include them even there.

**Comment by ghost** [comment]
#292 started adding interface files. All modules besides page components have interface files now. We can refine those interfaces soon.

The interface for page components needs a little thought. It looks like we can use abstract types for the type of `default`, since no ReScript React components will be referencing these page components. I need to review ReScript basics a little more to have a proper understanding.

**Comment by ghost** [comment]
Note: Research whether the return type for `getStaticProps` should always be a promise or can sometimes be a promise and sometimes be a plain object.

UPDATE: The return type is always a promise according to the official Typescript bindings below.

**Comment by ghost** [comment]
Here are Typescript bindings for getStaticProps: https://github.com/vercel/next.js/blob/bfac04dcbcaac4093c30a03e1a7e3aa91d066b9f/packages/next/types/index.d.ts#L95 .

**Comment by ghost** [comment]
For page components that implement getStaticPaths, we can implement a module that wraps an implementation of getStaticPathsHelper, so that the `fallback` json attribute is added by the wrapper.

**Comment by ghost** [comment]
#325 adds interface files for all page components.

We should do one more pass over the page components to see if we can consolidate types with type parameters. At that time, we should also introduce more accurate bindings for `getStaticProps` and `make`. We should also consider whether we want to refine the types in `common/App.resi`. Then we can close this issue.

After #253 is complete, we may introduce more sharing between page module definitions by using functors.

**Comment by agarwal** [comment]
@kanishka-work Consider whether this can be closed. We have ideas on how to implement improved interfaces, but those are new issues. If every module now has an interface, I'd close this.

**Comment by ghost** [comment]
> We should do one more pass over the page components to see if we can consolidate types with type parameters. At that time, we should also introduce more accurate bindings for getStaticProps and make. We should also consider whether we want to refine the types in common/App.resi. Then we can close this issue.

We will create follow-up issues to deal with these tasks.
