### ISSUE TITLE
Anonymously publish unsupported starter for nextjs

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#280]
Let's get other people relying on the same stack of tools as next.ocaml.org, so that others can benefit from it and fork it. The audience is other ocaml companies who are building a marketing website.

* create an anonymous account on gitlab.com or github.com. do not use a company in the name of the account
* create an empty repo with all interaction, such as issues and other features, disabled
* copy the basic skeleton of this project into that repo
* draft an announcement for discuss.ocaml.org below
* create a readme
* make the repo public
* publish discuss.ocaml.org announcment

See issues with label blocking-starter-template to understand the remaining work before the starter template can be published.

**Comment by ghost** [comment]
This starter might help with onboarding new full time contributors.

**Comment by agarwal** [comment]
This is a good idea. Let's keep it in mind, but closing this issue since it's not directly related to this project.
