### ISSUE TITLE
Running Wish List

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#283]
Update this description to add general long term wish list items.

* Add a description of the design assumptions (e.g. which screen sizes are supported) to the README, so that people filing bugs have a good understanding of whether a given issue is a bug or an intentional design decision
* Dark mode
* Rewrite using unbundled development tools and es6 dynamic imports (e.g. snowpack, vite-react), use simpler client rendering only
* OCaml top level on the homepage
* Make use of Melange and JSOO to implement portions of the site
* Optimize the produced html and deploy process to minimize energy use
* Add a wiki server
* Add a code of conduct

**Comment by rdavison** [comment]
Reviewed this during an internal meeting and concluded that the items were either already being tracked elsewhere, or we would no longer work on them.  Therefore we have decided to close this issue.
