### ISSUE TITLE
Prepare for merging into ocaml.org repository

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#300]
- [ ] Rename the master branch to `v3`.
- [ ] Update Vercel to use `v3` as the production branch and filter which branches to deploy.
- [ ] Add temporary instructions to contributing.md to prefix all branches with `v3/`.
- [ ] Add a `v3` label to all issues and PR's to be able to easily filter `v3` issues after this repository gets merged with `ocaml.org`.
- [ ] Consider whether dependabot or stalebot need to be modified to adjust to residing within the `v3` branch and adjust as needed.

**Comment by avsm** [comment]
For now, we're going to try to hold this as a separate repository, since it is very distinct from the v2.ocaml.org site.  This way we won't run into any intersection problems between bots and deployers running on either one.
