### ISSUE TITLE
Avoid dynamic class names

### ISSUE THREAD

**Issue by agarwal** [ocaml/v3.ocaml.org-rescript#314]
[Tailwind's purge logic](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html) disallows dynamically constructing class names. Or rather, it requires the static name to exist somewhere. Else, the class gets purged in production builds. I mistakenly introduced this problem in a new `Section` component.

Originally reported in https://github.com/ocaml/v3.ocaml.org/pull/218#discussion_r622467315.

**Comment by ghost** [comment]
This isn't a problem in the master branch. I removed `Section` component while updating the PR in this commit: https://github.com/ocaml/v3.ocaml.org/pull/218/commits/dedad104444699a75b0c95b04698edda9d9ab308 .

**Comment by agarwal** [comment]
Ah okay, thanks.
