### ISSUE TITLE
Integrate external content and parsing library (`ood`)

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#335]
Consider tradeoffs in how tightly to integrate with the external content repository. Implement the selected approach, including updating the Contributing documentation as well as the CI build.

**Comment by agarwal** [comment]
@rdavison I've added you to this issue also. You might have some insight on how to handle an external dependency like this that is tightly co-developed. @kanishka-work already started the PR.

Anil said he doesn't want it to be git submodule since that leads to lots of "update submodule" type of commits. However, without that, it's not obvious to me how to run CI on PRs here that have a companion PR in `ood`.

**Comment by ghost** [comment]
> "update submodule" type of commits

In case its not obvious to Richard, there would be commits to `ood` for every data edit, not just changes to ocaml type definitions. I think of `ood` as similar to a flat file, offline RDBMS.

**Comment by ghost** [comment]
It's almost like we need to use semantic versioning in the `ood/lib` bsconfig, and have the `package.json` in this project use a version range that rejects major version upgrades. This wouldn't solve the problem of cloning the tip of master and encountering a version of the ood library that is too new, but it would cause a clearer error when there is a mismatch. 

Essentially, we want the newest git commit that contains an acceptable version of the `ood/lib` package. I don't know how to accomplish this with the absolute minimum amount of glue code.

**Comment by ghost** [comment]
I decided to forgo this approach: #330 .

**Comment by ghost** [comment]
Done in #329 . Awaiting post merge code review.

**Comment by ghost** [comment]
The git commit noise which leads us to want to avoid git submodules prompts me towards a traditional rdbms approach. If the data was stored in an rdbms with strapi or WordPress acting as a headless CMS, then ood could be trimmed down to being a library of data types and routines for fetching data. Once the git repo only houses code, then a git submodule would be a viable solution.

With strapi, you could have a local development instance backed by sqlite. This would address the issue of having a branch work with a data schema that is different from the production schema.

This is all hypothetical since we are using netlify cms.

**Comment by ghost** [comment]
We can close this issue once we have verified the following workflows work as desired:
* Edit a content file in `ood` and observe the changes in the locally running site.
* Modify a data type to add an additional field, propagate needed changes, and observe a page using the new field in the locally running site.

**Comment by agarwal** [comment]
@kanishka-work @rdavison I believe this got done as part of #202. Is it QA'd as Kanishka requests above? Can we close?

**Comment by rdavison** [comment]
> Edit a content file in ood and observe the changes in the locally running site.

Done

> Modify a data type to add an additional field, propagate needed changes, and observe a page using the new field in the locally running site.

Done, though I did have to rerun the `make` command when I did this.

**Comment by rdavison** [comment]
Closing as I have QA'd this task as @kanishka-work requested above and observed the desired workflows.
