### ISSUE TITLE
Implement new dropdown menus with icons

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#337]
Designs are in Figma file V1 under 'Navbar'. Re missing icons: I am adding them to the Figma design today. 
<img width="1026" alt="Screenshot 2021-05-12 at 14 27 26" src="https://user-images.githubusercontent.com/73180976/117982709-31c82580-b32e-11eb-84f0-dfca7e4f21f3.png">

**Comment by ghost** [comment]
Thanks for creating this issue.

As an internal note, this issue overlaps with #125

**Comment by ILeandersson** [comment]
Here are updated screenshots with new icons and copy 
<img width="934" alt="Screenshot 2021-05-14 at 16 15 35" src="https://user-images.githubusercontent.com/73180976/118293695-d3d44300-b4d1-11eb-8102-40de03746861.png">
<img width="273" alt="Screenshot 2021-05-14 at 16 15 43" src="https://user-images.githubusercontent.com/73180976/118293705-d59e0680-b4d1-11eb-88ad-1a74607961a0.png">

**Comment by ghost** [comment]
The updated footer is below. Let's just leave this issue open until the footer has been updated.

![image](https://user-images.githubusercontent.com/1385802/120046406-14f34980-bfe0-11eb-86cf-58e333f386b4.png)

**Comment by ghost** [comment]
I am closing this since the new issue https://github.com/ocaml/v3.ocaml.org/issues/416 now tracks the comment above.
