### ISSUE TITLE
Change 'Industry' to 'Principles'

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#339]
Change in navbar, footer, and  and search for any other occurrences.

<img width="607" alt="Screenshot 2021-05-12 at 14 35 08" src="https://user-images.githubusercontent.com/73180976/117983883-422cd000-b32f-11eb-8c52-7e6c00acdf85.png">

<img width="759" alt="Screenshot 2021-05-12 at 14 53 49" src="https://user-images.githubusercontent.com/73180976/117986822-de57d680-b331-11eb-81d6-792b67d78476.png">

**Comment by agarwal** [comment]
I've generalized this issue to change the term everywhere.
