### ISSUE TITLE
Footer: Change 'Industry' to 'Principles' 

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#342]
Per this example: 
<img width="759" alt="Screenshot 2021-05-12 at 14 53 49" src="https://user-images.githubusercontent.com/73180976/117986822-de57d680-b331-11eb-81d6-792b67d78476.png">

**Comment by agarwal** [comment]
I generalized #339 such that this issue is now a duplicate.
