### ISSUE TITLE
Create module type signature for page modules

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#343]
Context: This refactoring is part of a series of refactorings to standardize the implementation of NextJS page module. (A nextjs page module is a combination of logic for fetching data at build time as well as a React component rendering the "main content" area of the page with the previously fetched data). The final refactoring in a later issue may involve defining a variant for all possible pages and having `common/App.res` make use of that variant.

Currently, the NextJS page modules which correspond to Rescript modules in the `/pages` directory implement an interface that conforms to a few general variations. The purpose of this issue is to explicitly model this fact using type signatures. At a minimum, let's refactor the existing pages into something like the following signatures:

```rescript
// Signature for a typical page
{
  // how do we want to deal with common fields like "title"? 
  type pageContent = {
     title: string,
     pageDescription: Js.Nullable.t<string>, // this will become option<string> after we have made other prerequisite improvements
     .... 
  }
  type props = {
     content: pageContent
   }
   @react.component
   let make: (~content: pageContent) => React.element
   let getStaticProps: Next.GetStaticProps<props, unit, unit>
   let default: {"content": pageContent} => React.element
}

// Signature for a page with colliding page name. Here is an example: "/history" vs "/community/history".
{
  type pageContent = {
     title: string,
     pageDescription: Js.Nullable.t<string>,
     .... 
  }
  type props = {
     content: pageContent
   }
   @react.component
   let make: (~content: pageContent) => React.element
   module Params: {
     type t // each page implementation will define this type to match the slug field name
   }
   let getStaticProps: Next.GetStaticProps<props, Params.t, unit>
   let default: {"content": pageContent} => React.element
   let getStaticPaths: Next.GetStaticPaths.t<Params.t>
}

// Signature for a dynamic url page. The current example of this is "/resources/[tutorial].res".
{
   // same as above, but allow for the two signatures to become different over time
}
```

Some of the existing pages will need small modifications to have them conform to these new signatures.

When working on this issue, we may choose to take this refactoring further if additional ideas occur to us. For example, there is some boilerplate in defining `getStaticPaths` which could be automated. Also, we might want to reduce the surface area of NextJS that we expose through the `GetStaticProps` bindings.

It is useful to note that the props value returned by getStaticProps is used by App.res as well as the React component rendering the page.

**Comment by agarwal** [comment]
> // signature for a typical page
> // signature for a page with colliding page name

The two signatures are similar. Some thoughts:
- Second signature should `include` the first one.
- Or could possibly reduce to a single signature by doing `let getStaticPaths: option<Next.GetStaticPaths.t<Params.t>>`. That's not enough since you also have a `Params` sub-module in the second signature, but mentioning this as a useful general trick.

**Comment by ghost** [comment]
We should provide more details on the type of pageContent. Will it make use of type parameters?

**Comment by ghost** [comment]
The shared fields may become title, pageDescription, and pageLayout, with a default value of MainLayout for the pageLayout field.

**Comment by ghost** [comment]
@rdavison has almost completed this.

**Comment by ghost** [comment]
I consider this issue complete.

**Comment by ghost** [comment]
Review of PR #438, file https://github.com/ocaml/v3.ocaml.org/pull/438/files#diff-a4c32feea76ffea143422fecb8c5dc31e4c5b546c23e925d4d5aadcb4466d8f4R97 :

Please add a source code comment with link(s) to documentation that you used to discover the ReScript documentation for type parameters such as `S with type t := Arg.t and type params = Arg.Params.t)`. This will help future maintainers quickly onboard.

**Comment by rdavison** [comment]
The main work of this issue was completed on Jun 16th, with the merging of PR #438. The issue has not been closed because of the outstinding review comment which is being addressed below:

-----

> Please add a source code comment with link(s) to documentation that you used to discover the ReScript documentation for type parameters such as S with type t := Arg.t and type params = Arg.Params.t). This will help future maintainers quickly onboard.

Explaining features of ReScript/OCaml is out of scope for the documentation in this project.

**Comment by ghost** [comment]
> Explaining features of ReScript/OCaml is out of scope for the documentation in this project.

I understand this sentiment. The reason why I asked for this particular documentation link is because the syntax is not documented on rescript-lang.org, so it will be hard to onboard new contributors, who will probably want to understand the Page functor implementation, after they start using it. I usually aspire to provide breadcrumbs for people when I use an undocumented feature of a library or language.
