### ISSUE TITLE
Start using types when referencing Tailwind utility classes

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#347]
We currently do not use the entire surface area of Tailwind utility classes. Let's start using types to provide stronger checks and to constrain which utility classes are available for use. 

We reference Tailwind classes as parameters to reusable React components, as well as directly in JSX implementing a given React component. The set of classes that are typically used as parameters is a very small subset of the total surface area. These parameters typically represent attributes which involve layout that extends beyond the reusable component (e.g. margin-bottom) or which style the reusable component (e.g. background color). The parameters constitute the API exposed to developers implementing a specific page with a set of reusable components, so we may want to prioritize polishing the modeling of these types first.

Below is a map of total [surface area of Tailwind CSS ](https://tailwindcomponents.com/cheatsheet/) (which is a thin abstraction above CSS):
![image](https://user-images.githubusercontent.com/1385802/118034850-71940a80-b338-11eb-9097-5b36f045c457.png)

Let's define a `Tailwind` module. Initially, we can populate this module with a submodule for `Margin`. The `Margin` module can consist of one variant to cover all the currently used values for `mb`. We could define similar variants for `mt`, `ml`, etc. I am not certain that these are the best long term abstractions for modeling `Margin`, but we can refactor it later as our perspective sharpens.

Design question: how should we model responsive variants such as `lg:mt-10`? Also, we sometimes want the parameters to reusable component to provide all the responsive variants in one argument such as `mt-0 sm:mt-4 lg:mt-8`. How should we model such a parameter?

Ideally, we would know all the margin values that are useful upfront and only expose those. For example, we might only want to expose `mt-0`, `mt-2`, `mt-4`, `mt-8`, and `mt-16`, and hide all other values. Then we could define a variant which only exposed those values. Right now, we don't know all the useful values, so we will define a variant with the known useful values and expand the definition of the variant later, as we discover additional useful values.

**Comment by rdavison** [comment]
> Also, we sometimes want the parameters to reusable component to provide all the responsive variants in one argument such as mt-0 sm:mt-4 lg:mt-8. How should we model such a parameter?

If they're defined as polymorphic variants, then it should be simple enough to constuct an array of them.

**Comment by jonludlam** [comment]
FYI I'm trying something similar in voodoo- https://github.com/ocaml-doc/voodoo/blob/main/gen/tailwind.ml

**Comment by ghost** [comment]
This issue reminds me of this recent ReScript forum thread: https://forum.rescript-lang.org/t/bs-css-layout-appareance-properties/1304. I imagine there are high quality discussions of these questions within some styled-components, emotion, or tailwind css forum.

**Comment by ghost** [comment]
One pattern that has come up a few times is passing in marginBottom for small breakpoints and marginRight for larger breakpoints, so we might be able to come up with a marginAfter type.

**Comment by ghost** [comment]
We modeled one utility class group, margin-bottom, in the PR #367. I will create follow-up issues to model other common utility classes.

**Comment by ghost** [comment]
Here is another project that has applied types to tailwind utility classes: https://github.com/phthhieu/re-tailwind/blob/master/src/TW.re.

**Comment by ghost** [comment]
- [ ] Finish reviewing https://github.com/ocaml/v3.ocaml.org/pull/367

**Comment by ghost** [comment]
We have started to denote classes of components. Some components are meant to be used by page implementors. Other components are meant to be used as building blocks for implementing the component library.

The types that we use to constrain the parameters for components used by page implementors should be very constrained. The types that we use to constrain the parameters for building block components should allow a much wider range of values.
