### ISSUE TITLE
Revisit CI once Vercel is back up

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#353]
Recently we have made some changes to the Makefile which could affect our CI builds, however we are unable to test them. Once @avsm restores CI access, we'll need to make sure that the build can be run in Vercel. In addition, let's try to simplify how we run the build. I think it should be possible to reuse existing targets instead of implementing a CI-specific target.

TODO:

- [x] Reimplement how we do the CI build so that it uses the same targets as the regular build. 
- ~~[ ] Narrow the scope of our required `node` version. See: https://github.com/ocaml/v3.ocaml.org/issues/202#issuecomment-827163519 and https://github.com/ocaml/v3.ocaml.org/issues/202#issuecomment-827093447~~

**Comment by rdavison** [comment]
>  Reimplement how we do the CI build so that it uses the same targets as the regular build.

Done as part of https://github.com/ocaml/v3.ocaml.org/pull/363

**Comment by ghost** [comment]
I see a sporadic failure on one of the dependabot PR's. My best guess is that the build failed when restoring a cache with 0.6.8 and then trying to install 0.6.10 over it. I haven't dug deeper to understand exactly what caused the failures. The caches may have all been fixed after later runs, which could explain why later runs become green.

![image](https://user-images.githubusercontent.com/1385802/118999744-87b55280-b958-11eb-89d0-504f4d0af0d4.png)

I think I have been encountered this condition: 

> When a new Git branch is created, there will not be a cache for that specific branch. Instead, the last Production Deployment cache will be used and a new branch cache will be created.

So, something could be wrong in the build cache resulting from the last build of the master branch. I will try merging something to master to trigger updating of the build cache.

**Comment by rdavison** [comment]
> Narrow the scope of our required node version. See: #202 (comment) and #202 (comment)

After a little discussion, we decided this was unnecessary. The reasons are as follows:
- Overly specific version constraints tend to look more and more like lockfiles (so why have lockfiles in the first place?)
- When versions are less specific, automation can take care of upgrading for things like security fixes.
- When the automation breaks, we can easily use a previous lockfile to roll back.

**Comment by rdavison** [comment]
Closing as I have verified that the build succeeds in CI.  Here is a screenshot that shows a ready status. 
![Screen Shot 2021-05-20 at 2 13 19 PM](https://user-images.githubusercontent.com/630055/119029866-2fda1400-b977-11eb-8a8f-0add08572408.png)
