### ISSUE TITLE
Fix key generation in header navigation code

### ISSUE THREAD

**Issue by avsm** [ocaml/v3.ocaml.org-rescript#382]
See https://github.com/ocaml/v3.ocaml.org/pull/376#discussion_r638175430 and a followup to #339

**Comment by ghost** [comment]
I am happy to take this issue. I will.assign it to myself for now. Jon can assign it to himself if he particularly wants to work on it.

**Comment by ghost** [comment]
This issue will most likely be addressed as part of one of the PR's that break off from #385, so I haven't bothered starting it. Jon also started a branch and found that #385 should suffice.

**Comment by ghost** [comment]
This issue will become irrelevant as the navigation implementation is changed.
