### ISSUE TITLE
Remove nvm from Makefile

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#383]
We have decided to no longer use `nvm` as the singular dependency in our Makefile as it was difficult to work with. Instead, we now want the user to install `npx` as the singular dependency.  Since `npx` is distributed via the `node` toolchain, the new recommendation shall be to simply install the Latest LTS Version 14 of Node.js as a system dependency.

**Comment by rdavison** [comment]
~~Discussed internally and we decided it was probably still OK to keep the nvm dependency. Closing this as: Won't Fix.~~

**Comment by rdavison** [comment]
Reopened this issue, as we have now decided that we really do want to remove `nvm` from the Makefile. I have updated the issue description with the latest decision.

**Comment by ghost** [comment]
- [x] Please update the contributing file to note which versions of node are acceptable.

**Comment by ghost** [comment]
> Please update the contributing file to note which versions of node are acceptable.

This was done in #409.

@agarwal Please close this issue when you merge #409.
