### ISSUE TITLE
Failures during `npx esy build` on Vercel

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#386]
I'm inconsistently encountering failures when npx esy build runs on Vercel.

Here are the logs of an example failure: https://vercel.com/ocaml/v3-ocaml-org/GavUpR38SnBufdS8FuBME8px3efj.

Vercel appears to try to download a previous matching build cache, and then timeout:
```
...
15:09:10.665 | Looking up build cache...
15:09:11.066 | Build cache found. Downloading...
15:09:37.146 | Build Cache not found
```

Then there is a failure when building dune:
```
15:10:32.051 | Running "make build"
15:10:32.057 | export ESY__PREFIX=$PWD/node_modules/.esy &amp;&amp; npx esy build
15:10:32.218 | info esy build 0.6.10 (using esy.json)
15:10:32.220 | info building @opam/seq@opam:base@d8d7de1d
15:10:32.220 | info building @opam/ocamlbuild@opam:0.14.0@6ac75d03
15:10:32.220 | info building @opam/cmdliner@opam:1.0.4@93208aac
15:10:32.220 | info building @opam/ocamlfind@opam:1.9.1@b748edf6
15:10:32.266 | info building @opam/seq@opam:base@d8d7de1d: done
15:10:32.267 | info building @opam/dune@opam:2.8.5@83fb0224
15:10:32.843 | error: build failed with exit code: 1
15:10:32.843 | build log:
15:10:32.843 | # esy-build-package: building: @opam/dune@opam:2.8.5
15:10:32.844 | # esy-build-package: pwd: /vercel/path0/node_modules/.esy/3/b/opam__s__dune-opam__c__2.8.5-6253c026
15:10:32.844 | # esy-build-package: running: 'ocaml' 'bootstrap.ml' '-j' '4'
15:10:32.844 | esy-build-package: unable to resolve command: ocaml
15:10:32.844 | &nbsp;
15:10:32.844 | building @opam/dune@opam:2.8.5
15:10:32.844 | esy: exiting due to errors above
15:10:32.868 | make: *** [build] Error 1
15:10:32.878 | Error: Command "make build" exited with 2
```

Is this a race condition where ocaml hasn't finished building/installing first?

We should consider disabling `esy build` in the Makefile, so that new contributors don't have to encounter this issue while we proceed to understand the root cause and apply an appropriate fix. Alternatively, we can keep `esy build`, but make the build command a noop and remove all dependencies from "devDependencies" and see if another error occurs or if it's specific to dune.

**Comment by ghost** [comment]
Usually, when this occurs, if I manually go into Vercel, and trigger a redeploy with the build cache disabled, the redeploy succeeds.

**Comment by ghost** [comment]
If the cache is too large, we might choose to only cache a few core esy dependencies.

**Comment by rdavison** [comment]
Interesting.  I suspect that you're right about the cache size. Afaik, Vercel's documentation doesn't really say anything about this.  I would be fine eliminating esy from the cache and just making sure it gets reinstalled from scratch every time.

**Comment by ghost** [comment]
If we don't observe any errors in preview builds for a week, then we can consider this issue partially resolved.

The Vercel build will take about six minutes for now. We can resume trying to use some form of caching on an experimental branch until we have all the corner cases worked out. I will create an issue for optimizing Vercel build to track this work once it starts.

**Comment by ghost** [comment]
This error occurred many times within the dune package build. I haven't figured out why it happened so frequently within dune, rather than arbitrary dependencies.

**Comment by ghost** [comment]
This hasn't occurred since we introducing cleaning in the CI build. This will occur again later if we remove the clean step, but we can address that if we attempt that later on.
