### ISSUE TITLE
Generalize loading nvm during development

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#387]
It's possible to install nvm using homebrew or other methods. When a developer installs nvm using homebrew, the nvm data directory and binary directory are not the same. nvm normally uses the same directory for both purposes. Let's modify the loading of nvm in our makefile to be flexible enough to handle the homebrew case (and possibly other conditions).

I experimented a bit with .SHELLFLAGS, but I wasn't able to get SHELL to be set to the user's shell. It's probably possible, but I don't know how to do it at the moment.

Using the following command pattern did seem to work: `$$SHELL -i -c 'nvm use && ... `.

~~For now, we will simply enhance the makefile to detect whether nvm.sh is in the default location. If it's not in the default location, we will assume nvm was installed by brew and use the brew command to find the nvm directory.~~

**Comment by shreyaswikriti** [comment]
I faced a similar issue in Ubuntu. I had previously installed nvm using the curl command. While running the makefile command I got an error.
![Screenshot from 2021-05-28 17-17-42](https://user-images.githubusercontent.com/57635473/120112110-20867200-c192-11eb-97be-6c43968a3a00.png)
The issue was solved by running the `nvm install` command.

**Comment by ghost** [comment]
@shreyaswikriti I don't completely understand what error happened when you encountered the message "Error 3." If you can recreate the error later, it would be helpful to have more detail. In particular, what happens when you run `bash -c 'source /home/aarav/nvm.sh && nvm --version'`.

**Comment by shreyaswikriti** [comment]
@kanishka-work `bash: /home/aarav/nvm.sh: No such file or directory` is the output of `bash -c 'source /home/aarav/nvm.sh && nvm --version'`.

**Comment by rdavison** [comment]
I don't think `nvm.sh` would be located at `$HOME` unless you specifically put it there? @kanishka-work @shreyaswikriti 

Anyways, just to chime in here, I opened a PR https://github.com/ocaml/v3.ocaml.org/pull/396 where I attempt to address this problem by requiring that `nvm` is installed and available from within a Bash session.  You can test if it's installed correctly if you can run the following command successfully: `bash -ic 'nvm --version'`

**Comment by ghost** [comment]
> I don't think nvm.sh would be located at $HOME unless you specifically put it there?

You are right. I didn't expand $NVM_DIR correctly.

**Comment by ghost** [comment]
@rdavison The `nvm.sh` script has a number of places which use `return 3`. Before each instance, `nvm` usually logs the failure. Let's enhance the makefile to log the messages from `nvm` when there is an error.

**Comment by rdavison** [comment]
We have decided to stop working on this issue and instead replace the effort by pursuing #383.
