### ISSUE TITLE
Delete watch-and-serve target

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#406]
I would delete watch-and-serve target. A while back we talked about it briefly. watch-and-serve would only be correct if we introduced some other logic to repeatedly run build and serve on each file change.

_Originally posted by @kanishka-work in https://github.com/ocaml/v3.ocaml.org/pull/396#discussion_r645306579_

**Comment by ghost** [comment]
This was done in #432.
