### ISSUE TITLE
Update the Industrial Users page to the new and improved version

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#415]
There has been a new design of the Industrial Users page that looks like this:

<img width="435" alt="Screenshot 2021-06-09 at 12 44 17" src="https://user-images.githubusercontent.com/73180976/121348570-6a085700-c920-11eb-9b51-ea7e55ec6bdc.png">

It would be good to update the version on the live website

**Comment by shreyaswikriti** [comment]
Hello, Can I work on this?

**Comment by ghost** [comment]
This will be done as part of #481.

**Comment by ghost** [comment]
@rdavison If we consolidated the designs for the titles of the Academic Excellence page and this page, then we could implement a second page template: "logo cloud page."
