### ISSUE TITLE
Footer: add 'academic excellence' under Principles

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#416]
The list under Principles should lookalike this:

<img width="168" alt="Screenshot 2021-06-09 at 13 24 08" src="https://user-images.githubusercontent.com/73180976/121353720-14cf4400-c926-11eb-9fcc-39e63aed8a23.png">

And currently looks like this: 

<img width="149" alt="Screenshot 2021-06-09 at 13 27 00" src="https://user-images.githubusercontent.com/73180976/121354019-61b31a80-c926-11eb-8cd6-5602acb39426.png">

we should add 'Academic Excellence' here

**Comment by ghost** [comment]
This was done in #426.
