### ISSUE TITLE
'Packages' needs its own page

### ISSUE THREAD

**Issue by ILeandersson** [ocaml/v3.ocaml.org-rescript#418]
Currently 'Packages' on the V3 page redirects to 'Best Practices', it would be good if 'packages' had its own page.

**Comment by ghost** [comment]
We had set Packages to link to a deployed version of docs.ocaml.org. That deployed version no longer appears active. @jonludlam Please update the link to another deployed instance, if possible.

**Comment by ghost** [comment]
The current PR #429 can also update the packages link.

**Comment by ghost** [comment]
Let's use docs-staging.ocaml.org for now, with a rewrite rule in next.config.js?

**Comment by ghost** [comment]
This will be solved as part of #462. For now, when previewing the site, the page won't go anywhere, but the final production site will display the proper packages content.
