### ISSUE TITLE
Remove alias for React.string

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#423]
As for your comments about `let s = React.string` and `module Link = Next.Link`, the answer is yes. We tend to avoid creating aliases in the first place because they can obfuscate the code through indirection....

_Originally posted by @rdavison in https://github.com/ocaml/v3.ocaml.org/pull/393#discussion_r645767128_

**Comment by ghost** [comment]
@agarwal I think we should consider keeping the `s` alias. From my perspective, a react component that is using jsx is essentially trying to communicate html and css to the reader. Anything besides html and css is syntactic noise that interferes with the reader's concentration on understanding the combination of html and css being expressed. In such a scenario, react.array, react.string, and anything else of that nature is noise.

**Comment by ghost** [comment]
By similar reasoning as above, it would also be really nice if we could create an alias for the Classname module, which could be called "Cn".

**Comment by ghost** [comment]
(The Next.Link aliases will be gone once #254 is done, so there is no need to remove it before then.)

**Comment by agarwal** [comment]
If people agree that some particular aliases are useful, then fine. In that case, they should be defined in `Import.res`. That is meant to be the single source that developers of this project need to look at to discover such decisions.

Keep in mind my general objections to aliases:
- There are now two names for the same thing. Which one to use? Do you want to disallow `React.string` or can people use that in addition to `s`.
- Aliases like this optimize for writing, but I think code should be optimized for reading. When someone new to the project goes directly to a file and sees `s`, they won't know what that is.
- Grep'ing for `React.string` works. Grep'ing for `s` doesn't.

**Comment by ghost** [comment]
> Aliases like this optimize for writing, but I think code should be optimized for reading.

This is the only part where we might differ. I see "s" as optimizing for reading of html, by reducing the interruptions/noise from ReScript.

I don't feel strongly on this, so I think Richard should just consider the options and apply whichever rule he prefers across the codebase in one large PR.

**Comment by ghost** [comment]
This is being tracked in #514.
