### ISSUE TITLE
nvm-exec not found

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#45]
```
$ nvm exec npx yarn@1.22 install
Found '/Users/ashish/solvuu/ocamlorg2/.nvmrc' with version <14.15.1>
Running node v14.15.1 (npm v6.14.8)
bash: /Users/ashish/.nvm/nvm-exec: No such file or directory
```
using `nvm use` instead works around the issue

**Comment by ghost** [comment]
I scanned through issues on NVM and didn't get any immediate matches for this error. Add a note in readme about avoiding "NVM exec", then close this issue.

**Comment by agarwal** [comment]
I updated the title to be a more accurate description of the error being reported.

I also investigated this further. In my shell login scripts I was doing `export NVM_DIR=~/.nvm`. I'm not sure why. I probably read some documentation about `nvm` when I first installed it, and decided this was a good setting. After removing this, `nvm exec` runs fine. We can later create a new issue about using `nvm exec` in our build scripts if we decide that is a good idea.

**Comment by ghost** [comment]
I ended up liking `nvm install` , which performs `nvm use` automatically and obviates the need for `nvm exec`.

**Comment by agarwal** [comment]
As discussed in a call, we probably should avoid invoking `nvm install` in every build command. That's going too far. Usually build commands assume you first have a bunch of dependencies correctly installed, and don't re-assert that every time.

**Comment by ghost** [comment]
Everything has been updated to split `install-deps` from `build`. We need a check in the make target for `rescript-watch` and `next-dev` which refuses to proceed if the package.json is newer(?) than node_modules contents. This is low priority. I will mull on this and come up with a concrete implementation later.
