### ISSUE TITLE
Pages should have access to params

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#458]
Pages should have access to the params because they often contain important information, such as the language that the page is in. Components need to know this information in order to create links to other pages.

**Comment by ghost** [comment]
I only expect two params to be used: lang and slug. Maybe we can restrict users to either selecting lang or `langWithSlug<t>` types?

**Comment by ghost** [comment]
We discussed over Slack and there is a working proposal for generalizing Params.Tutorial.

**Comment by rdavison** [comment]
The idea is that we can change the Tutorial module into a functor called Slug, and as part of the argument, we pass the name of the json field we want to parse as a slug. This way it is not necessary to duplicate the logic encoded in the Tutorial module.

**Comment by ghost** [comment]
We noted that this issue will also enable implementing #487.

**Comment by ghost** [comment]
(cc: @patricoferris This issue will simplify implementing individual pages for academic institutions)
