### ISSUE TITLE
Replace 404.re with 404.js

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#479]
ReScript seems to be unable to export a default value when the name of the module begins with a number, such as in the module `404.re`. One solution is to create a `404.js` file which references another module (`src/FourZeroFour.res`). Unfortunately, this solution *also* doesn't work because something (bsb?) is automatically deleting `404.js`.  Therefore, we had to implement it as `404.res` using `%%raw()` to export a default value correctly.

Clearly this solution is very roundabout, and ideally we should just figure out how to prevent `404.js` from being deleted.

_Originally posted by @kanishka-work in https://github.com/ocaml/v3.ocaml.org/pull/478#discussion_r669177045_

**Comment by ghost** [comment]
This issue will become irrelevant, so I am closing.
