### ISSUE TITLE
Update the link to "Install OCaml" on the homepage

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#490]
- [ ] Please update the link to "Install OCaml" on the homepage

_Originally posted by @kanishka-work in https://github.com/ocaml/v3.ocaml.org/issues/445#issuecomment-868724186_

**Comment by ghost** [comment]
@renatoalencar This is the related issue.

You can also remove "resources/basics".

**Comment by cdaringe** [comment]
🤚

**Comment by ghost** [comment]
We may want to enhance the Route module to allow for adding string fragments or even compile time checked fragments. I will make note of this in the open ood issue.
