### ISSUE TITLE
Document Components in Storybook

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#492]
Right now we have some components of the component library factored out, but it's not easy to see at a glance what they are and what they look like.  Recently a page was added, `pages/storybook` which begins the process of documenting the components.  We need to go through all the components of our library and render them on the page and give examples.

**Comment by ghost** [comment]
For historical context, we considered using the actual Storybook framework, but multiple times, ReScript forum members discouraged using the Storybook framework because it is complicated to integrate and use. Therefore, we implemented a lightweight imitation of it.

**Comment by rdavison** [comment]
After merging #482 and #516 the Storybook page now contains 96 examples of the following 46 components:

* StoryCard.CornerTitleLogo
* StoryCard.CornerLogoCenterTitle
* ShortWideCard
* CallToAction.Embedded
* CallToAction.Simple
* StackedList.BasicWithIcon
* StackedList.BasicWithAuxiliaryAttribute
* TitleHeading.Large
* TitleHeading.OverBackgroundImage
* TitleHeading.MarkdownMedium
* MediaObject.Small
* MediaObject
* LogoCloud
* Hero
* HighlightInQuadrants
* CallToAction.General
* CallToAction.TransparentWide
* Table.Simple
* Table.Regular
* Stats
* MarkdownPage.Body
* Testimonials
* Timeline
* UserLevelIntroduction
* MediaCarousel
* Blog2
* ContentGrid
* VerticalHighlightCard
* SectionContainer.VerySmallCentered
* SectionContainer.SmallCentered
* SectionContainer.MediumCentered
* SectionContainer.MediumCentered2
* SectionContainer.LargeCentered
* SectionContainer.ResponsiveCentered
* SectionContainer.FullyResponsiveCentered
* SectionContainer.NoneFilled
* CardGrid
* Page.Basic
* Page.HighlightItem
* Page.TitleOverBackgroundImage
* Page.TopImage
* Page.Unstructured
* Page.MainContainer.Centered
* Page.MainContainer.NarrowCentered
* Page.MainContainer.NarrowCentered
* Page.MainContainer.None
