### ISSUE TITLE
Remove Tailwind module

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#522]
Despite my best efforts to make it less so, the Tailwind module continues to require writing code that is overly verbose.  I believe we should replace it with a simpler abstraction.

Then simplest abstraction is to just have no abstraction, and just use the CSS classnames directly as strings; and at one step higher on the abstraction chain, we can define simple variants such as:
```rescript
// foo.res
type t = ...

@react.component
let make = (~content: t, ~size: [< #Small | #Medium | #Large ]) => {
  let size = switch size {
    | #Small => ...
    | #Medium => ...
    | #Large => ...
  }
  <div classNames=`foo bar baz ${size}`>
    {  ...content... }
  </div>
}

```

For external styling such as margin, I propose we continue to use simple tailwind classes with a wrapper div at the callsite, for example:
```rescript
let content = ...
<div className="mb-4">
  <Foo content size=#Medium />
</div>
```

**Comment by cdaringe** [comment]
> just use the CSS classnames directly as strings

this is essential for the purgecss algorithm to kick in anyway, ya?

**Comment by rdavison** [comment]
> > just use the CSS classnames directly as strings
> 
> this is essential for the purgecss algorithm to kick in anyway, ya?

They just need to be represented as strings *somewhere* in your code, it doesn't necessarily have to be within a component.  So you could do things like:
```rescript
let marginBottom =
  switch marginBottom {
  | Large => "mb-24"
  | Medium => "mb-12"
  | Small => "mb-2"
  }
  
<div className=`foo bar ${marginBottom}`>
  ...
</div>
```  

Then you don't actually pass around the strings, but the variants.  However, the one thing the docs caution against is constructing CSS classes programmatically.  So, no concatenation allowed. This would be an example of the kind of code that would break the purgecss algorithm:
```rescript
<div className={"mb-" ++ string_of_int(marginBottom)}>
  ....
</div>
```

That being said, we were in fact doing concatenation in the Tailwind module (this is before I knew about purgecss). My latest PR removes the Tailwind module entirely anyways.

**Comment by rdavison** [comment]
> > just use the CSS classnames directly as strings
> 
> this is essential for the purgecss algorithm to kick in anyway, ya?

Did a [QA pass](https://github.com/ocaml/v3.ocaml.org/pull/528#issuecomment-915364203) of the pages before merging, and it looks like deleting the Tailwind module ended up fixing a bug I hadn't even realized I introduced related to the CSS purging.
