### ISSUE TITLE
Create a sitemap file

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#67]
Implement something like the following: https://docs.kontent.ai/tutorials/develop-apps/optimize-your-app/sitemaps-for-seo

(Low priority)

**Comment by ghost** [comment]
Reopen later if this becomes a priority

**Comment by ghost** [comment]
Nextjs will generate this. Relates to accessibility

**Comment by shreyaswikriti** [comment]
@kanishka-work, How do I generate nextjs sitemap. I searched and found this result  https://www.npmjs.com/package/next-sitemap
Is there any proficient and simple way to generate a sitemap? Need the sitemap thing for implementing Pa11y-ci tool

**Comment by ghost** [comment]
I agree that https://www.npmjs.com/package/next-sitemap might work. You can try it out and see if it runs successfully. If that tool does not function properly, then I would aim for less automation for now. There are libraries like https://www.npmjs.com/package/sitemap which you can use from a javascript (or ReScript) script, which start from a list of URL's that you provide, and produce the sitemap file.
