### ISSUE TITLE
Code review for Industrial Users html and css

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#77]
Original: https://play.tailwindcss.com/mNyPy3g9Ko
Latest: https://play.tailwindcss.com/UIyUDSL5s9

**Comment by ghost** [comment]
`  <div class="text-lg max-w-prose mx-auto"> `

Note: Although all text below has a size specified, the size specified here controls the width calculated by `max-w-prose`

**Comment by ghost** [comment]
`prose-indigo` customizes the link color. It uses some complex customization to convert `indigo-600` into `prose-indigo`. Will need to understand and use this when changing the link color to orange.

**Comment by ghost** [comment]
The placement of background patterns is complex. We can keep it and treat it as a black box for now. Consider removing it altogether, as well as all the `relative` and `absolute` classes used to support it.

**Comment by ghost** [comment]
This page will have another design soon, discontinue this review

**Comment by agarwal** [comment]
> discontinue this review

Yes, we still need to iterate on the design in Figma first.
