### ISSUE TITLE
Code review for footer html and css

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#78]
original: https://play.tailwindcss.com/sDvt5fPLI1
latest:

**Comment by ghost** [comment]
The code is not that complex. Once the content is selected, the footer should be complete.

**Comment by agarwal** [comment]
I agree this code is easy to write and the main issue is deciding on the exact content. However, when we do implement it, I think we should improve the html. There is a lot of duplication of code in it right now, which can be avoided once it is in a rescript file.

**Comment by ghost** [comment]
You can see the refactoring that I walked back in the commits here: https://github.com/solvuu-inc/ocamlorg2/pull/79/commits

It's a little painful doing a three way "merge" between edits to tailwind components from design changes and refactorings in ReScript, so I walked back the refactorings for now.
